import turtle
screen = turtle.Screen()
screen.bgcolor('bisque')
screen.title('Meu desenho digital')

alex = turtle.Turtle()
alex.pencolor('lightblue')
alex.pensize(5)

alex.forward(80)
alex.right(90)
alex.forward(80)
alex.right(90)
alex.forward(80)
alex.right(90)
alex.forward(80)
alex.right(90)
alex.forward(160)
alex.right(90)
alex.forward(80)
alex.right(90)
alex.forward(80)

alex.left(90)
alex.forward(80)
alex.right(90)
alex.forward(80)
alex.right(90)
alex.forward(80)

alex.right(90)
alex.forward(160)
alex.right(90)
alex.forward(80)
alex.right(90)
alex.forward(80)
alex.right(90)

for aColor in ['blue', 'lightpink', 'lightgray', 'lightgreen', 'orange']:
    alex.color(aColor)
    alex.circle(100)
alex.left(90)
alex.forward(97)
alex.color('red')
alex.forward(3)
screen.exitonclick()
